# Use an official Node runtime as a parent image
FROM node:20.8.0-alpine3.18 AS builder

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./package.json ./
COPY ./package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the Angular app
RUN npm run build --configuration=production

# Use a lighter-weight base image for the production environment
FROM nginx:alpine3.18

# Copy the NGINX config
COPY nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Set the working directory to /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

# Copy the built Angular app to the container
COPY --from=builder /app/dist ./

# Expose port 8089
EXPOSE 8089

# Start the Node.js web server when the container starts
CMD nginx -g "daemon off;"
