FROM node:latest AS builder

WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./package.json ./
COPY ./package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

CMD npm run start
#
# FROM node:current-alpine
#
# WORKDIR /app
#
# COPY --from=builder /app/dist ./
#
# CMD node saver.js
